In [0]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
#normalizing the dataset of handwritten digits
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
#creating the neural network
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),#Flattens the input for the First layer into a single vector in this case 28x28 
  tf.keras.layers.Dense(128, activation='relu'),#First Layer of the network with 128 nodes 
  tf.keras.layers.Dropout(0.2),#Dropout layer is to avoid the problem of overfitting, the parameter passed here is the rate or the amount of input to be dropped
  tf.keras.layers.Dense(10)#Second Layer with 10 Nodes
])

In [4]:
predictions = model(x_train[:1]).numpy() #scores for each class 
predictions 

array([[ 0.30323648, -0.1290077 ,  0.73175365,  0.01964809, -0.42933786,
        -0.5662416 , -0.50083816,  0.56010693,  0.17163986, -0.17091192]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy() #converting the scores to probabilities

array([[0.123817  , 0.08036353, 0.19005658, 0.09324367, 0.05951511,
        0.0519004 , 0.05540833, 0.16008022, 0.10854968, 0.07706554]],
      dtype=float32)

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)# Defining the loss function

In [7]:
loss_fn(y_train[:1], predictions).numpy() 

2.9584289

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2967 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1406 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1060 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0874 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0756 - accuracy: 0.9765


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0728 - accuracy: 0.9786


[0.07283269613981247, 0.978600025177002]

In [14]:
import numpy as np
results = model.predict(x_test[:5])
print(np.argmax(results, axis=1))

[7 2 1 0 4]
